.TH prioritizer 1 "May 08, 2017" "version 1.1" "USER COMMANDS"
.SH NAME
prioritizer \- help interactively sort priorities
.SH SYNOPSIS
.B prioritizer
input-filename output-filename

.SH DESCRIPTION
Sometimes it is necessary to sort many priorities from greatest to least.
This program helps with that by taking in the name of an input file and an output file,
interactively helping the user sort the lines on the input file, and then writing to the output file.

.SH AUTHOR
Noah Williams (thecrazymancan@gmail.com)

.SH SEE ALSO
sort(1)
